major_project/chms/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='chms'

urlpatterns=[
    path("login/",auth_views.LoginView.as_view(template_name="chms/patient_login.html"),name="login_patient"),
    path("logout/", auth_views.LogoutView.as_view(template_name="chms/thanks.html"), name="logout"),
    path("register/patient/",views.PatientCreate,name='register_patient'),
    path("dashboard/patient/",views.PatientDashboard,name='patient_dashboard'),
    path("dashboard/patient/update/<str:username>/",views.PatientUpdateView,name='patient_update'),
    path("dashboard/doctor/patient/list/",views.PatientListView,name='patient_list'),
    path('dashboard/<int:pk>/detail',views.PatientDetailView.as_view(),name='patient_detail'),
    path("test/",views.TestPageView.as_view(),name="test"),
    path("thanks/",views.ThanksPageView.as_view(),name="thanks"),

    path("create/appointment/<str:username>/",views.AppointmentCreate,name="create_appointment"),
    path("dashboard/patient/list/appointment/<str:username>/",views.AppointmentListView,name="list_appointment"),
    #path('',views.AppointmentListView.as_view(),name='appointment_list'),
    #path("update/appointment/",views.AppointmentUpdate,name="update_appointment"),
    path("delete/appointment/<int:pk>/",views.AppointmentDeleteView,name="delete_appointment"),

    path("create/bed/<str:username>/",views.BedCreate,name="create_bed"),
    path("list/bed/<str:username>/",views.BedListView,name="list_bed"),
    #path("update/appointment/",views.AppointmentUpdate,name="update_appointment"),
    path("delete/bed/<int:pk>/",views.BedDeleteView,name="delete_bed"),

    path("login/",auth_views.LoginView.as_view(template_name="chms/doctor_login.html"),name="login_doctor"),
    path("register/doctor/",views.DoctorCreate,name='register_doctor'),
    path("dashboard/doctor/",views.DoctorDashboard,name='doctor_dashboard'),
    path("dashboard/doctor/update/<str:username>/",views.DoctorUpdateView,name='doctor_update'),
    path("list/doctor/",views.DoctorListView,name='doctor_list'),
    path("dashboard/doctor/list/appointment/<str:username>/",views.DoctorAppointmentListView,name="appointment_doctor"),
    path("confirm/<int:pk>/",views.ConfirmAppointment,name='confirm_appointment'),
    path("dashboard/doctor/list/shifts/<str:username>/",views.ShiftsListView,name="shifts_list"),


    path("login/",auth_views.LoginView.as_view(template_name="chms/admin_login.html"),name="login_admin"),
    path("dashboard/admin/",views.AdminDashboard,name='admin_dashboard'),
    path("list/users/",views.UserListView,name="user_list"),
    path("delete/users/<int:pk>/",views.UserDeleteView,name="delete_user"),
    #path("create/shift/<str:username>/",views.ShiftCreate,name="create_shift"),
    #path('list/shifts/<str:username>/',views.ShiftsListView,name="list_shifts"),
]

major_project/major_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('chms/',include('chms.urls',namespace="chms")),
    path('chms/',include('django.contrib.auth.urls')),
    path('about/',views.AboutView.as_view(),name='about'),
    path('contactUs/',views.ContactView.as_view(),name='contact'),
]

major_project/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hospital Management | About Us</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
     integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
    integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <link rel="stylesheet"  href="{% static 'css/master.css' %}">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>
  <body>
    <nav class="nav nav_top">
      <div class="logo">
          <a href="{% url 'home' %}"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
      </div>
      <div class="nav_side">
         <a href="{% url 'about'%} ">About Us</a>
          <a href="{% url 'contact' %}">Contact us</a>
      </div>
    </nav>
    <div class="about_us">
    <h1>About Us</h1>
    <div class="about_content">
      <p>WELCOME TO Covid-19 HOSPITAL MANAGEMENT SYSTEM!<br>
           The place to find the best doctors and facilities for Covid patients. We thoroughly check the quality of our goods, working only with reliable doctors so
           that you only receive the best quality facilities and treatments.

           We believe in high quality treatment and exceptional patient service.
      </p>
  </div>
<hr>
  <h1>Our Mission</h1>
  <p>During the pandemic situation it is very typical to maintain overall data, so we are trying to develop a little bit solution for this.
    Our missiion is to provide our covid patients with high quality yet budget-friendly treatment. We offer all of this while providing excellent facilities
      and friendly support.
      We always keep an eye on the latest trends and put our customers’ wishes first. That is why we have satisfied customers all over the world, and are thrilled
       to be a part of the this industry.<br>
      The interests of our customers are always top priority for us, so we hope you will enjoy our products as much as we enjoy making them available to you.
  </p>
  <h1>Our Vision</h1>
  <p>Our Vision lies to bring in a best services and facilities as per our patients need<br> with Great price and Discounts.
      <br><br>
      ”Spend Less,Live Better"
  </p>
    </div>

    <footer>
      <div class="footer_logo">
          <a href="{% url 'home' %}"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
      </div>
      <div class="pages">
          <h3>Pages</h3>

          <a href="{% url 'about'%} ">About Us</a>
          <a href="{% url 'contact' %}">Contact us</a>

      </div>
      <div class="contact">
          <h3>Contact Us</h3>
          <a href="https://api.WhatsApp.com/send?phone=+919838623258" target=_black><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
          <a href="tel:+919838723258"><i class="fa fa-phone" aria-hidden="true"></i></a>
          <a href="mailto: support@abcd.ai"><i class="fa fa-envelope" aria-hidden="true"></i></a>
      </div>
      <hr>
      <p>Copyright &copy; 2022 Covid-19 Hospital Management System</p>
  </footer>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="
  sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="
  sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

  </body>
</html>

major_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
     <title> Hospital Management</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
        integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">


        <link rel="stylesheet"  href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet"  href="{% static "css/master.css" %}">
</head>
<body>
    <nav class="nav nav_top">
        <div class="logo">
            <a href="#"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
        </div>
        <div class="nav_side">

            <a href="{% url 'about'%} ">About Us</a> |
            <a href="{% url 'chms:logout' %}">Logout</a> |
            <a href="{% url 'contact' %}">Contact us</a>
        </div>
    </nav>
{% block body %}{% endblock body %}
    <div class="feedback">
        <h2>Write a review</h2>
        <div class="feedback_form">
            <form name="submit-googlesheet">
                <input type="text" name="Name" placeholder="Name"><br>
                <input type="email" name="Email" placeholder="Email Id"><br>
                <input type="number" name="Number" placeholder="Contact Number"><br>
                <textarea rows="5" cols="7"name="Review"  placeholder="Write a review"></textarea><br>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
<footer>
    <div class="footer_logo">
    </div>
    <div class="pages">
        <h3>Pages</h3>
        <a href="about.html">About Us</a>
        <a href="{% url 'contact' %}">Contact Us</a>

    </div>
    <hr>
    <p>Copyright &copy; Covid-19 Hospital Mangement </p>
</footer>

     {% block body %}{% endblock body %}

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="
sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="
sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>

major_project/templates/contactUs.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
     <title>Hospital Mangement | Contact Us</title>
     <link rel="stylesheet"  href="{% static "css/master.css" %}">

     <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <nav class="nav nav_top">
        <div class="logo">
            <a href="{% url 'home' %}"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
        </div>
        <div class="nav_side">

            <a href="{% url 'about' %}">About Us</a>
            <a href="{% url 'contact' %}">Contact Us</a>

        </div>
    </nav>

    <div class="contact_us">
        <h2>Contact Us</h2>
        <div class="g_map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.967845617231!2d77.62147541404345!3d12.973908418339786!2m3!1f0!2f0!3f0!3m2!1i1024!2i
            768!4f13.1!3m3!1m2!1s0x3bae16b0f2af61b3%3A0xb7d458638b286620!2sSwami%20Vivekananda%20Rd%2C%20Cambridge%20Layout%2C%20Jogupalya%2C%20Bengaluru%2C%20Karnataka
            !5e0!3m2!1sen!2sin!4v1630771064422!5m2!1sen!2sin" width="100%" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
        <div class="contact_content">
            <p><b>Address: Sindhi Camp Road,Jaipur,Rajasthan</b></p>
            <p><b>Call: +919838723258</b></p>
            <p><b>Mail: support@chms.ai</b></p>
        </div>
    </div>
<footer>
    <div class="footer_logo">
        <a href="#"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
    </div>
    <div class="pages">
        <h3>Pages</h3>
        <a href="{% url 'about' %}">About Us</a>
        <a href="{% url 'contact' %}">Contact Us</a>
    </div>
    <div class="contact">
        <h3>Contact Us</h3>
        <a href="https://api.WhatsApp.com/send?phone=+919838623258" target=_black><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
        <a href="tel:+919838723258"><i class="fa fa-phone" aria-hidden="true"></i></a>
        <a href="mailto: support@chms.ai"><i class="fa fa-envelope" aria-hidden="true"></i></a>
    </div>
    <hr>
    <p>Copyright &copy; 2021 1stop All rights reserved</p>
</footer>

<script type="text/JavaScript">
    const scriptURL = 'https://script.google.com/macros/s/AKfycby3d-kGog1UjjT3wRKWA2Np71HJtNNWFGzS1aVNuAVf8mg7itc6rY6tGaVdl533lMA/exec'
            const form = document.forms['submit-googlesheet']
            form.addEventListener('submit', e => {
              e.preventDefault()
              fetch(scriptURL, { method: 'POST', body: new FormData(form)})
                .then(response => alert("Thanks you for the review....! Have a nice day ahead....!"))
                .catch(error => console.error('Error!', error.message))
            })
</script>
</body>
</html>

major_project/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title> Hospital Management</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
    integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static 'css/master.css' %}">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <nav class="nav nav_top">
        <div class="logo">
            <a href="{% url 'home' %}"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
        </div>
        <div class="nav_side">


           <a href="{% url 'about'%} ">About Us</a>
            <a href="{% url 'contact' %}">Contact us</a>
            <div class="subnav">
                <button class="subnavbtn">Register <i class="fa fa-caret-down"></i></button>
                <div class="subnav-content">
                  <a href="{% url 'chms:register_patient' %}">Patient</a>
                  <a href="{% url 'chms:register_doctor' %}">Doctor</a>
                </div>
              </div>
              <div class="subnav">
                <button class="subnavbtn">Login <i class="fa fa-caret-down"></i></button>
                <div class="subnav-content">
                  <a href="{% url 'chms:login_patient' %}">Patient</a>
                  <a href="{% url 'chms:login_doctor' %}">Doctor</a>
                  <a href="{% url 'chms:login_admin' %}">Admin</a>
              </div>
        </div>
    </nav>
    <div class="main">
        <div class="main_content">
          <h1>Welcome to CovidCare ! </h1>
        </div>

        <style>
          .main{
            background-image: url({% static "images/background.png" %});

            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            height: 80vh;
          }
        </style>
    </div>
    <div class="keypoint">
        <h2>OUR KEY HIGHLIGHTS</h2>
        <div class="key_container">
            <div class="key_content">
                <li>110 Emergency Beds.</li>
                <li>750 Total Pickups(Monthly)</li>
                <li>Patient-Centric Approach.</li>
                <li>Cutting-Edge Technology.</li>
                <li>Transparent Pricing</li>
                <li>Coordinated Care</li>
                <li>Efficient and Empathetic Nursing Staff.</li>
                <li>Timely Communication.</li>
            </div>
            <div class="key_img">
                <img src="{% static "images/image1.jpeg" %}">
            </div>
        </div>
    </div>
    <hr>

    <div class="testi">
        <h2>OUR SERVICES</h2>
        <div class="testi_container">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                  <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                  <div class="item active">
                    <div class="item_img">
                        <img src="{% static "images/bed.jpg" %}">
                    </div>
                    <div class="item_content">
                        <h3>Hospital Beds</h3>

                    </div>

                  </div>
                  <div class="item">
                        <div class="item_img">
                            <img src="{% static "images/ventilator.jpg" %}">
                        </div>
                        <div class="item_content">
                            <h3>Ventilators</h3>

                        </div>
                    </div>
                  <div class="item">
                        <div class="item_img">
                            <img src="{% static "images/am.jpg" %}">
                        </div>
                        <div class="item_content">
                            <h3>Ambulance</h3>

                        </div>
                   </div>
                   <div class="item">
                    <div class="item_img">
                        <img src="{% static "images/laboratory.jpg" %}">
                    </div>
                    <div class="item_content">
                        <h3>Test Laboratory</h3>

                    </div>
                </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
        </div>
    </div>

    <hr>

    <div class="team">
        <h2>COVID-19 GUIDELINES</h2>
        <div class="team_container">
            <div class="team_video">
              <iframe width="560" height="315" src="https://www.youtube.com/embed/xVu_I6WCsto" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="team_content">
                <p><b>Here are some Guidelines:</b><br>1.Get Vaccinated and stay up to date on your COVID-19 vaccines.<br>2.Wear a mask.<br>
                    3.Stay 6 feet away from others<br>4.Avoid poorly ventilated spaces and crowds.<br>5.Test to prevent spread to others
                    <br>6.Wash your hands often with soap and water for at least 20 seconds especially after you have been in
                    a public place, or after blowing your nose, coughing, or sneezing.<br>7.If soap and water are not readily available,
                    use a hand sanitizer that contains at least 60% alcohol. Cover all surfaces of your hands and rub them together until
                    they feel dry.
                    </p>
            </div>
        </div>
    </div>

    <div class="feedback">
        <h2>Write a review</h2>
        <div class="feedback_form">
            <form name="submit-feedback">
                <input type="text" name="Name" placeholder="Name"><br>
                <input type="email" name="Email" placeholder="Email Id"><br>
                <textarea rows="8" cols="7"name="Review"  placeholder="Write a review"></textarea><br>
                <button type="submit">Submit</button>
            </form>
        </div>

        <style>
            .feedback{
              background-image: url({% static "images/imagebkg.webp" %});
              background-size: cover;
            }
          </style>

    </div>

<footer>
    <div class="footer_logo">
        <a href="{% url 'home' %}"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
    </div>
    <div class="pages">
        <h3>Pages</h3>

        <a href="{% url 'about'%} ">About Us</a> |
        <a href="{% url 'contact' %}">Contact us</a>

    </div>
    <div class="contact">
        <h3>Contact Us</h3>
        <a href="https://api.WhatsApp.com/send?phone=+919838623258" target=_blank><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
        <a href="tel:+919838723258"><i class="fa fa-phone" aria-hidden="true"></i></a>
        <a href="mailto: support@abcd.ai"><i class="fa fa-envelope" aria-hidden="true"></i></a>
    </div>
    <hr>
    <p>Copyright &copy; 2022 Covid-19 Hospital Management System</p>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="
sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="
sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

<script type="text/JavaScript">
     const scriptURL = 'https://script.google.com/macros/s/AKfycby3d-kGog1UjjT3wRKWA2Np71HJtNNWFGzS1aVNuAVf8mg7itc6rY6tGaVdl533lMA/exec'
    const form = document.forms['submit-feedback']
            form.addEventListener('submit', e => {
              e.preventDefault()
              fetch(scriptURL, { method: 'POST', body: new FormData(form)})
                .then(response => alert("Thanks you for the review....! Have a nice day ahead....!"))
                .catch(error => console.error('Error!', error.message))
            })

</script>

</body>
</html>