major_project/chms/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='chms'

urlpatterns=[
    path("login/",auth_views.LoginView.as_view(template_name="chms/patient_login.html"),name="login_patient"),
    path("logout/", auth_views.LogoutView.as_view(template_name="chms/thanks.html"), name="logout"),
    path("register/patient/",views.PatientCreate,name='register_patient'),
    path("dashboard/patient/",views.PatientDashboard,name='patient_dashboard'),
    path("dashboard/patient/update/<str:username>/",views.PatientUpdateView,name='patient_update'),
    path("dashboard/doctor/patient/list/",views.PatientListView,name='patient_list'),
    path('dashboard/<int:pk>/detail',views.PatientDetailView.as_view(),name='patient_detail'),
    path("test/",views.TestPageView.as_view(),name="test"),
    path("thanks/",views.ThanksPageView.as_view(),name="thanks"),

    path("create/appointment/<str:username>/",views.AppointmentCreate,name="create_appointment"),
    path("dashboard/patient/list/appointment/<str:username>/",views.AppointmentListView,name="list_appointment"),
    #path('',views.AppointmentListView.as_view(),name='appointment_list'),
    #path("update/appointment/",views.AppointmentUpdate,name="update_appointment"),
    path("delete/appointment/<int:pk>/",views.AppointmentDeleteView,name="delete_appointment"),

    path("create/bed/<str:username>/",views.BedCreate,name="create_bed"),
    path("list/bed/<str:username>/",views.BedListView,name="list_bed"),
    #path("update/appointment/",views.AppointmentUpdate,name="update_appointment"),
    path("delete/bed/<int:pk>/",views.BedDeleteView,name="delete_bed"),

    path("login/",auth_views.LoginView.as_view(template_name="chms/doctor_login.html"),name="login_doctor"),
    path("register/doctor/",views.DoctorCreate,name='register_doctor'),
    path("dashboard/doctor/",views.DoctorDashboard,name='doctor_dashboard'),
    path("dashboard/doctor/update/<str:username>/",views.DoctorUpdateView,name='doctor_update'),
    path("list/doctor/",views.DoctorListView,name='doctor_list'),
    path("dashboard/doctor/list/appointment/<str:username>/",views.DoctorAppointmentListView,name="appointment_doctor"),
    path("confirm/<int:pk>/",views.ConfirmAppointment,name='confirm_appointment'),
    path("dashboard/doctor/list/shifts/<str:username>/",views.ShiftsListView,name="shifts_list"),


    path("login/",auth_views.LoginView.as_view(template_name="chms/admin_login.html"),name="login_admin"),
    path("dashboard/admin/",views.AdminDashboard,name='admin_dashboard'),
    path("list/users/",views.UserListView,name="user_list"),
    path("delete/users/<int:pk>/",views.UserDeleteView,name="delete_user"),
    #path("create/shift/<str:username>/",views.ShiftCreate,name="create_shift"),
    #path('list/shifts/<str:username>/',views.ShiftsListView,name="list_shifts"),
]

major_project/major_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('chms/',include('chms.urls',namespace="chms")),
    path('chms/',include('django.contrib.auth.urls')),
    path('about/',views.AboutView.as_view(),name='about'),
    path('contactUs/',views.ContactView.as_view(),name='contact'),
]

major_project/chms/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from . import models
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from chms.models import Patient,Doctor,Appointment,Bed,Shift,User

bld_grp=(
        (1, 'A+'),
        (2, 'A-'),
        (3, 'B+'),
        (4, 'B−'),
        (5, 'AB+'),
        (6,'AB−'),
        (7,'O+'),
        (8,'O−'))
gender=(
    (1,'FEMALE'),
    (2,'MALE'),
    (3,'OTHER'),
    )

sts=(
    (1,'First Dose'),
    (2,'Second Dose'),
    )
rtype=(
       (1,'PRIVATE ROOM'),
       (2,'EMEREGENCY WARD'),
       (3,'COVID-19 WARD'),
       (4,'3-BED SHARED'),
)
sps=(
     (1,'Orthopedics'),
     (2,'Gynecology'),
     (3,'Dermatology'),
     (4,'Pediatrics'),
     (5,'Radiology'),
     (6,'Ophthalmology'),
     (7,'ENT'),
     (8,'Neurology'),
     (9,'Urology'),
     (10,'Surgery'),

)


class PatientCreateForm(forms.ModelForm):
    fname=forms.CharField(label="First Name")
    lname=forms.CharField(label="Last Name")
    dob = forms.DateField(label="Date Of Birth (yyyy-mm-dd)")
    blood_grp=forms.CharField(label="Blood Group",widget=forms.Select(choices=bld_grp))
    gnd=forms.CharField(label="Gender",widget=forms.Select(choices=gender))
    ph_no=forms.CharField(label="Phone Number")
    email_id=forms.EmailField(label="Email")
    vacc_sts=forms.CharField(label="Vaccination Status",widget=forms.Select(choices=sts))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    class Meta:
        model = models.Patient
        fields = ['fname','lname','username','dob','age','blood_grp','gnd','ph_no','email_id','vacc_sts']

        def save(self, commit=True):
            user = super(PatientCreateForm,self).save(commit=False)
            user.username = self.cleaned_data["username"]
            user.password=self.cleaned_data['password']
            if commit:
                user.save()
            return user


class DoctorCreateForm(forms.ModelForm):
    fname=forms.CharField(label="First Name")
    lname=forms.CharField(label="Last Name")
    gnd=forms.CharField(label="Gender",widget=forms.Select(choices=gender))
    ph_no=forms.CharField(label="Phone Number")
    email_id=forms.EmailField(label="Email")
    specialist=forms.CharField(label="Doctor's Specialization",widget=forms.Select(choices=sps))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    class Meta:
        model = models.Doctor
        fields = ['fname','lname','username','gnd','ph_no','email_id','specialist']

        def save(self, commit=True):
            user = super(DoctorCreateForm, self).save(commit=False)
            user.username = self.cleaned_data["username"]
            user.password=self.cleaned_data['password']
            if commit:
                user.save()
            return user

class AppointmentCreateForm(forms.ModelForm):
    #patient= forms.ModelMultipleChoiceField(queryset=Patient.objects.all())
    class Meta:
        model = models.Appointment
        fields = ['patient','doctor','app_date','app_time','desc']

        def save(self, commit=True):
            appointment = super(AppointmentCreateForm,self).save(commit=False)
            if commit:
                appointment.save()
            return appointment


class BedCreateForm(forms.ModelForm):
    room_type=forms.CharField(label="Room Type",widget=forms.Select(choices=rtype))
    class Meta:
        model = models.Bed
        fields = ['bed_number','patient','room_type']

        def save(self, commit=True):
            bed = super(BedCreateForm, self).save(commit=False)
            #user.username = self.cleaned_data["username"]
            #user.password=self.cleaned_data['password']
            if commit:
                bed.save()
            return bed

class ShiftsCreateForm(forms.ModelForm):
    sdate=forms.DateTimeField(label='Shift Date')
    stime=forms.DateTimeField(label='Shift Time')
    class Meta:
        model = models.Shift
        fields = ['doctor','sdate','stime']

        def save(self, commit=True):
            shift = super(ShiftsCreateForm,self).save(commit=False)
            if commit:
                shift.save()
            return shift

major_project/chms/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from chms.models import Patient,Doctor,Appointment,Bed,Shift
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,FormView
from django import forms
from chms.forms import PatientCreateForm,DoctorCreateForm,AppointmentCreateForm,BedCreateForm,ShiftsCreateForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from chms.models import Patient,Doctor,Appointment,Bed
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,FormView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from django.contrib.auth import get_user_model
User = get_user_model()

class TestPageView(TemplateView):
    template_name='chms/test.html'

class ThanksPageView(TemplateView):
    template_name='chms/thanks.html'

def PatientCreate(request):
    context={}
    if request.method == 'POST':
        form=PatientCreateForm(request.POST or None)
        if form.is_valid():
            form.save(commit=False)
            username=form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request,username=username, password=password)
            user=User.objects.create_user(username=username,password=password)
            user.save()
            form.save()
            messages.success(request,'account created successfully')
            patient=form.save()
            patient.save()
            messages.success(request, 'account created successfully')
            return redirect('login')
    else:
       form=PatientCreateForm()
    context['form']=form
    return render(request,"chms/patient_register.html", context)

@login_required(login_url='login')
def PatientDashboard(request):
    return render(request,'chms/patient_dashboard.html')

@login_required(login_url='login')
def PatientUpdateView(request,username):
    patient=get_object_or_404(Patient,username=username)
    form=PatientCreateForm(request.POST or None,instance=patient)
    context={}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect("chms:patient_dashboard")
    return render(request,'chms/patient_update.html',{'form':form})

def PatientListView(request):
    context={}
    patients=Patient.objects.all()
    context['patients']=patients
    return render(request,'chms/patient_list.html',context)


class PatientDetailView(LoginRequiredMixin,DetailView):
    model=Patient

#class PatientList(LoginRequiredMixin,ListView):
#    return render(request,"chms/register.html", context)

class PatientProfile(LoginRequiredMixin,TemplateView):
    pass


def DoctorCreate(request):
    context={}
    if request.method == 'POST':
        form=DoctorCreateForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            fname=form.cleaned_data['fname']
            lname=form.cleaned_data['lname']
            specialist=form.cleaned_data['specialist']
            username=form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request,username=username, password=password)
            user=User.objects.create_user(username=username,password=password)
            user.save()
            form.save()
            messages.success(request,'account created successfully')
            return redirect('login')
    else:
       form=DoctorCreateForm()
    context['form']=form
    return render(request,"chms/doctor_register.html", context)

@login_required(login_url='login')
def DoctorDashboard(request):
    return render(request,'chms/doctor_dashboard.html')

@login_required(login_url='login')
def DoctorUpdateView(request,username):
    doctor=get_object_or_404(Doctor,username=username)
    form=DoctorCreateForm(request.POST or None,instance=doctor)
    context={}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect("chms:doctor_dashboard")
    return render(request,'chms/doctor_update.html',{'form':form})

def DoctorAppointmentListView(request,username):
    context={}
    doctor = Doctor.objects.filter(username__iexact=username)
    appointment=Appointment.objects.all()
    context['appointment']=appointment
    return render(request,'chms/appointment_list_doctor.html',context)

def ConfirmAppointment(request,pk):
    return render(request,'chms/confirm_appointment.html')

def DoctorListView(request):
    context={}
    doctor= Doctor.objects.all()
    context['doctor']=doctor
    return render(request,'chms/doctor_list.html',context)

@login_required
def AppointmentCreate(request,username):
    context={}
    patient = Patient.objects.filter(username__iexact=username).first()
    doctor=Doctor.objects.all()
    if request.method == 'POST':
        form = AppointmentCreateForm(request.POST,instance=patient)
        if form.is_valid():
            form.save(commit=False)
            doctor=form.cleaned_data['doctor']
            app_date=form.cleaned_data['app_date']
            app_time=form.cleaned_data['app_time']
            desc=form.cleaned_data['desc']
            appointment=authenticate(request)
            appointment=Appointment.objects.create(patient=patient,doctor=doctor,app_date=app_date,app_time=app_time,desc=desc)
            appointment.save()
            form.save()
            messages.success(request,'appointment created')
            return redirect('chms:list_appointment',username=username)
    else:
        form = AppointmentCreateForm()
    context['form']=form
    return render(request,'chms/appointment_create.html',context)

def AppointmentListView(request,username):
    context={}
    patient = Patient.objects.filter(username__iexact=username)
    doctor=Doctor.objects.all()
    appointment=Appointment.objects.all()
    context['appointment']=appointment
    return render(request,'chms/appointment_list.html',{'appointment':appointment,'patient':patient,'doctor':doctor})

def AppointmentDeleteView(request,pk):
    #patient = Patient.objects.filter(username__iexact=username)
    appointment=Appointment.objects.get(pk=pk)
    appointment.delete()
    return redirect("chms:list_appointment",pk)

@login_required
def BedCreate(request,username):
    context={}
    patient = Patient.objects.filter(username__iexact=username).first()
    if request.method == 'POST':
        form = BedCreateForm(request.POST,instance=patient)
        if form.is_valid():
            form.save(commit=False)
            bed_number=form.cleaned_data['bed_number']
            room_type=form.cleaned_data['room_type']
            bed=authenticate(request)
            bed=Bed.objects.create(patient=patient,bed_number=bed_number,room_type=room_type)
            bed.save()
            form.save()
            messages.success(request,'bed booked')
            return redirect('chms:list_bed',username=username)
    else:
        form = BedCreateForm()
    context['form']=form
    return render(request,'chms/bed_create.html',context)

def BedListView(request,username):
    context={}
    patient = Patient.objects.filter(username__iexact=username)
    bed=Bed.objects.all()
    context['bed']=bed
    return render(request,'chms/bed_list.html',context)

def BedDeleteView(request,pk):
    bed=Bed.objects.get(pk=pk)
    bed.delete()
    return redirect("chms:list_bed",pk)

def ShiftsListView(request,username):
    context={}
    doctor= Doctor.objects.filter(username__iexact=username)
    shift=Shift.objects.all()
    context['shift']=shift
    return render(request,'chms/shifts_list.html',context)


@login_required(login_url='login')
def AdminDashboard(request):
    return render(request,'chms/admin_dashboard.html')

def UserListView(request):
    context={}
    users=User.objects.all()
    context['users']=users
    return render(request,'chms/users_list.html',context)

def UserDeleteView(request,pk):
    user = User.objects.get(pk=pk)
    user.delete()
    return redirect("chms:user_list",pk)

@login_required
def ShiftCreate(request,username):
    context={}
    doctor = Doctor.objects.all()
    if request.method == 'POST':
        form = ShiftsCreateForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            s_date=form.cleaned_data['s_date']
            s_time=form.cleaned_data['s_time']
            shift=authenticate(request)
            shift=Shift.objects.create(doctor=doctor,s_date=s_date,s_time=s_time)
            shift.save()
            form.save()
            messages.success(request,'Shift booked')
            return redirect('chms:shift_list',username=username)
    else:
        form = ShiftsCreateForm()
    context['form']=form
    return render(request,'chms/shift_create.html',context)

major_project/chms/templates/chms/appointment_list.html
{% load bootstrap5 %}
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hospital Management | Login</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
    integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <link rel="stylesheet"  href="{% static 'css/master.css' %}">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>


  <body>
    <nav class="nav nav_top">
      <div class="logo">
          <a href="{% url 'home' %}"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
      </div>

      <div class="nav_side">
         <a href="{% url 'about'%} ">About Us</a>
          <a href="{% url 'contact' %}">Contact us</a>
      </div>
    </nav>

<br><br><br><br>
<div class="card ">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom: 2px solid orange">View Appointment</h5>
        <td><a href="{% url 'chms:create_appointment' user.username %}" onclick="return confirm('Are you ready to add the record ?')" class="btn btn-danger">Add</a></td>
        <div class="table">
        <h1 class="text-success text-center"></h1>
        <table id="example" class="table table-striped table-bordered table-sm" style="width:80%">
            <thead>
                <tr>
                    <th>Doctor Name</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Description</th>
                </tr>
            </thead>

            <tbody>
            {% for i in appointment %}
              <tr>
                  <td>{{i.doctor}}</td>
                  <td>{{i.app_date}}</td>
                  <td>{{i.app_time}}</td>
                  <td>{{i.desc}}</td>
                  <td><a href="{% url 'chms:delete_appointment' i.id %}" onclick="return confirm('Are you ready to delete this record ?')" class="btn btn-danger">Delete</a></td>
              </tr>
            {% endfor %}
            </tbody>
        </table>
     </div>
    </div>
</div>

<footer>
    <div class="footer_logo">
        <a href="{% url 'home' %}"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
    </div>
    <div class="pages">
        <h3>Pages</h3>

        <a href="{% url 'about'%} ">About Us</a>
        <a href="{% url 'chms:register_patient' %}">Register</a>
        <a href="{% url 'contact' %}">Contact us</a>

    </div>
    <div class="contact">
        <h3>Contact Us</h3>
        <a href="https://api.WhatsApp.com/send?phone=+919838623258" target=_black><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
        <a href="tel:+919838723258"><i class="fa fa-phone" aria-hidden="true"></i></a>
        <a href="mailto: support@abcd.ai"><i class="fa fa-envelope" aria-hidden="true"></i></a>
    </div>
    <hr>
    <p>Copyright &copy; 2022 Covid-19 Hospital Management System</p>
</footer>

 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
 <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="
 sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>

 <!-- Latest compiled and minified JavaScript -->
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="
 sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

</body>
</html>

major_project/chms/templates/chms/bed_list.html
{% load bootstrap5 %}
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
    integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <link rel="stylesheet"  href="{% static 'css/master.css' %}">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <nav class="nav nav_top">
      <div class="logo">
          <a href="{% url 'home' %}"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
      </div>

      <div class="nav_side">
         <a href="{% url 'about'%} ">About Us</a>
          <a href="{% url 'contact' %}">Contact us</a>
      </div>
    </nav>

<br><br><br><br>
<div class="container card shadow m-5">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom: 2px solid orange">View  Bed Bookings</h5>
        <td><a href="{% url 'chms:create_bed' user.username %}" onclick="return confirm('Are you ready to add the record ?')" class="btn btn-danger">Add</a></td>
        <div class="container mt-5">
        <h1 class="text-success text-center"></h1>
        <table id="example" class="table table-striped table-bordered table-sm" style="width:80%">
            <thead>
                <tr>
                    <th>Bed Number</th>
                    <th>Patient Name</th>
                    <th>Room Type</th>
                </tr>
            </thead>

            <tbody>
            {% for i in bed %}
            <tr>
                <td>{{i.bed_number}}</td>
                <td>{{i.patient}}</td>
                <td>{{i.room_type}}</td>
                <td><a href="{% url 'chms:delete_bed' i.id %}" onclick="return confirm('Are you ready to delete this record ?')" class="btn btn-danger">Delete</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
     </div>
    </div>
</div>

<footer>
    <div class="footer_logo">
        <a href="#"><img src="{% static "images/CovidLogo.jpeg" %}" width="150"></a>
    </div>
    <div class="pages">
        <h3>Pages</h3>

        <a href="{% url 'about'%} ">About Us</a> |
        <a href="{% url 'contact' %}">Contact us</a>

    </div>
    <div class="contact">
        <h3>Contact Us</h3>
        <a href="https://api.WhatsApp.com/send?phone=+919838623258" target=_black><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
        <a href="tel:+919838723258"><i class="fa fa-phone" aria-hidden="true"></i></a>
        <a href="mailto: support@abcd.ai"><i class="fa fa-envelope" aria-hidden="true"></i></a>
    </div>
    <hr>
    <p>Copyright &copy; 2022 Covid-19 Hospital Management System</p>
</footer>

 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
 <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="
 sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>

 <!-- Latest compiled and minified JavaScript -->
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="
 sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

</body>
</html>

major_project/chms/templates/chms/patient_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Dashboard</title>
    <link rel="stylesheet" type="text/css"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/ds.css' %}">
</head>

<body>
    <div class="container">
        <div class="navbar">
            <div class="logo">
                <img style="width: 40px;" src="recycling.png" alt="">
                <span class="logoname"></span>
            </div>
            <div class="navitem">

            </div>
        </div>

        <div class="container-body">
            <div class="sidebar">
                <ul>
                    <li class="dashboard">
                        <i class="fa fa-dashcube"></i>
                        <a href="{% url 'chms:patient_dashboard' %}">Patient Dashboard</a>
                    </li>
                    <li>
                        <i class="fa fa-user"></i>
                        <a href="{% url 'chms:patient_update' user.username %}">Update Profile</a>
                    </li>
                    <li>
                        <i class="fa fa-calendar"></i>
                        <a href="{% url 'chms:list_appointment' user.username %}">Appointments</a>
                    </li>
                    <li>
                        <i class="fa fa-book"></i>
                        <a href="{% url 'chms:list_bed' user.username %}"> Bed/Room</a>
                    </li>
                    <li>
                        <i class="fa fa-book"></i>
                        <a href="{% url 'chms:doctor_list' %}">Doctors List</a>
                    </li>
                    <li>
                        <i class="fa fa-question-circle"></i>
                        <a href="{% url 'chms:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>

            <div class="main-body">
              <div class="lang">
              <h1>WELCOME! Hello, {{ user.username|default:'Guest' }}!</h1>
            </div>
                <div class="cards">
                    <div class="row row-1">
                        <div class="col">
                            <div
                            </div>
                        </div>

                        <div class="col">

                        </div>
                        <div class="col">
                            <div
                            </div>
                        </div>
                    </div>

                    <div class="row row-2">
                        <div class="col">
                            <div class="total-invoice">

                            </div>
                        </div>
                        <div class="col">
                            <div class="paid-invoice">

                            </div>
                        </div>
                        <div class="col">
                            <div class="unpaid-invoice">

                            </div>
                        </div>
                        <div class="col">
                            <div class="invoice-sent">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</body>

</html>